version: "3"
services:
  hexo-container:
    #build: .
    image: spurin/hexo
    container_name: hexo
    restart: always
    environment:
        - HEXO_SERVER_PORT=4000   
        - GIT_USER=ideameshdyx       # 改成自己的用户名，可以随便写一个 
        - GIT_EMAIL=ideameshdyx@gmail.com  # 改成自己的邮箱，可以随便写一个
        - TZ=Asia/Shanghai  # 时区
    tty: true
    volumes:
      - ../:/app
      - ~/.ssh:/root/.ssh
    ports:
      - "4000:4000"
    command: tail -f /dev/null  # 添加此命令以保持容器运行